version: 2
jobs:
  build:
    docker:
      - image:continuumio/anaconda:latest
    steps:
      - checkout
      - run:
           name: testing notebooks
           command: |
             make all
